name: Publish

on:
  release:
    types: [published]
    
permissions:
  contents: write 

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: linux ARM
            os: ubuntu-latest
            target: linux-arm64 
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
          - kind: macOS ARM
            os: macos-latest
            target: osx-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x  # Updated to .NET 8.0

      - name: Build
        shell: bash
        run: |
          release_name="${{ vars.SOFTWARE_NAME }}-${{ matrix.target }}"

          # Build everything
          dotnet publish src/AzureDevOpsLicenseChecker/AzureDevOpsLicenseChecker.csproj --framework net8.0 --runtime "${{ matrix.target }}" -c Release -o "${release_name}" \
            -p:PublishSingleFile=true -p:PublishTrimmed=true -p:SelfContained=true

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "${release_name}/${{ vars.SOFTWARE_NAME }}.exe*"
          else
            tar czvf "${release_name}.tar.gz" -C "${release_name}" ${{ vars.SOFTWARE_NAME }}
          fi

          # Delete output directory
          rm -r "${release_name}"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ vars.SOFTWARE_NAME }}*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}