name: Build and Create Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build for Linux x64
      run: dotnet publish -c Release -r linux-x64
      working-directory: src/AzureDevOpsLicenseChecker

    - name: Build for Linux ARM64
      run: dotnet publish -c Release -r linux-arm64
      working-directory: src/AzureDevOpsLicenseChecker

    - name: Build for Windows x64
      run: dotnet publish -c Release -r win-x64
      working-directory: src/AzureDevOpsLicenseChecker

    - name: Build for macOS x64
      run: dotnet publish -c Release -r osx-x64
      working-directory: src/AzureDevOpsLicenseChecker

    - name: Build for macOS arm64
      run: dotnet publish -c Release -r osx-arm64
      working-directory: src/AzureDevOpsLicenseChecker

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-artifacts
        path: |
          src/AzureDevOpsLicenseChecker/bin/Release/net8.0/linux-x64
          src/AzureDevOpsLicenseChecker/bin/Release/net8.0/linux-arm64
          src/AzureDevOpsLicenseChecker/bin/Release/net8.0/win-x64
          src/AzureDevOpsLicenseChecker/bin/Release/net8.0/osx-x64
          src/AzureDevOpsLicenseChecker/bin/Release/net8.0/osx-arm64
